list: $/sgdinstitute/funny404/models/message/columns.yaml
modelClass: SGDInstitute\Funny404\Models\Message
title: Message
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sgdinstitute/funny404/message/update/:id'
